platformname=Android
appiumport=4725

platformName=Android
platformVersion=11
automationName=UiAutomator2
deviceName=Samsung
androidapk=app-staging-release-universal.apk

browserstack=true
browserstackDevice=Samsung Galaxy S22 Ultra
browserstackOS=12.0
browserStackUser=zubairtest_MtSUdh
accessKey=zE428qbSBeJVyjLJa8LP
BROWSERSTACK_APP_ID=bs://141b9f0e7cc7e1946c7858f41fbc2d81f5728a5f
